# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-10-15 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('health_points', models.IntegerField()),
                ('level', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('trainer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('evolves_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.PokemonSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTrainers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='types',
            field=models.ManyToManyField(to='pokemon.PokemonTypes'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.PokemonSpecies'),
        ),
    ]
