# Generated by Django 3.2 on 2023-10-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
            ],
            options={
                'db_table': 'pokemon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'pokemon_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'pokemon_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'trainer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesType',
            fields=[
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokemon.pokemonspecies')),
            ],
            options={
                'db_table': 'species_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerItems',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pokemon.trainer')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'trainer_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeWeakness',
            fields=[
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='type_weaknesses', serialize=False, to='pokemon.pokemontype')),
            ],
            options={
                'db_table': 'type_weakness',
                'managed': False,
            },
        ),
    ]
